### PR TITLE
Upgrade broccoli-jshint to take advantage of broccoli-persistent-filter

### PR DESCRIPTION
**Pull request by johnnyshields**
Reduces build time

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by johnnyshields** [comment]
Thank you! Please cut a release when convenient.

**Comment by rwjblue** [comment]
Ya, will do. I'm traveling with spotty internet today. 

@dgeb - Would you mind releasing an update (we should also make sure to bump the blueprint for ember-mocha version if it isn't current)?

**Comment by dgeb** [comment]
Ok, just released v0.9.4 :shipit:

**Comment by rwjblue** [comment]
Thanks @dgeb!

**Pull request merged**
